// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type ASUWatchedClass struct {
	ent.Schema
}

func (ASUWatchedClass) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("user_id"), field.String("title"), field.String("instructor"), field.String("subject"), field.String("subject_number"), field.Time("tracked_at").Optional(), field.String("class_number"), field.String("term")}
}
func (ASUWatchedClass) Edges() []ent.Edge {
	return nil
}
func (ASUWatchedClass) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "ASU_Watched_Classes"}}
}
