// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ASUWatchedClass is the predicate function for asuwatchedclass builders.
type ASUWatchedClass func(*sql.Selector)
