// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ASU_Watched_Class is the predicate function for asu_watched_class builders.
type ASU_Watched_Class func(*sql.Selector)
