// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asu_watched_class"
	"attendr/watcher/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ASUWatchedClassQuery is the builder for querying ASU_Watched_Class entities.
type ASUWatchedClassQuery struct {
	config
	ctx        *QueryContext
	order      []asu_watched_class.OrderOption
	inters     []Interceptor
	predicates []predicate.ASU_Watched_Class
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ASUWatchedClassQuery builder.
func (awcq *ASUWatchedClassQuery) Where(ps ...predicate.ASU_Watched_Class) *ASUWatchedClassQuery {
	awcq.predicates = append(awcq.predicates, ps...)
	return awcq
}

// Limit the number of records to be returned by this query.
func (awcq *ASUWatchedClassQuery) Limit(limit int) *ASUWatchedClassQuery {
	awcq.ctx.Limit = &limit
	return awcq
}

// Offset to start from.
func (awcq *ASUWatchedClassQuery) Offset(offset int) *ASUWatchedClassQuery {
	awcq.ctx.Offset = &offset
	return awcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (awcq *ASUWatchedClassQuery) Unique(unique bool) *ASUWatchedClassQuery {
	awcq.ctx.Unique = &unique
	return awcq
}

// Order specifies how the records should be ordered.
func (awcq *ASUWatchedClassQuery) Order(o ...asu_watched_class.OrderOption) *ASUWatchedClassQuery {
	awcq.order = append(awcq.order, o...)
	return awcq
}

// First returns the first ASU_Watched_Class entity from the query.
// Returns a *NotFoundError when no ASU_Watched_Class was found.
func (awcq *ASUWatchedClassQuery) First(ctx context.Context) (*ASU_Watched_Class, error) {
	nodes, err := awcq.Limit(1).All(setContextOp(ctx, awcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{asu_watched_class.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) FirstX(ctx context.Context) *ASU_Watched_Class {
	node, err := awcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ASU_Watched_Class ID from the query.
// Returns a *NotFoundError when no ASU_Watched_Class ID was found.
func (awcq *ASUWatchedClassQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = awcq.Limit(1).IDs(setContextOp(ctx, awcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{asu_watched_class.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) FirstIDX(ctx context.Context) int {
	id, err := awcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ASU_Watched_Class entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ASU_Watched_Class entity is found.
// Returns a *NotFoundError when no ASU_Watched_Class entities are found.
func (awcq *ASUWatchedClassQuery) Only(ctx context.Context) (*ASU_Watched_Class, error) {
	nodes, err := awcq.Limit(2).All(setContextOp(ctx, awcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{asu_watched_class.Label}
	default:
		return nil, &NotSingularError{asu_watched_class.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) OnlyX(ctx context.Context) *ASU_Watched_Class {
	node, err := awcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ASU_Watched_Class ID in the query.
// Returns a *NotSingularError when more than one ASU_Watched_Class ID is found.
// Returns a *NotFoundError when no entities are found.
func (awcq *ASUWatchedClassQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = awcq.Limit(2).IDs(setContextOp(ctx, awcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{asu_watched_class.Label}
	default:
		err = &NotSingularError{asu_watched_class.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) OnlyIDX(ctx context.Context) int {
	id, err := awcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ASU_Watched_Classes.
func (awcq *ASUWatchedClassQuery) All(ctx context.Context) ([]*ASU_Watched_Class, error) {
	ctx = setContextOp(ctx, awcq.ctx, "All")
	if err := awcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ASU_Watched_Class, *ASUWatchedClassQuery]()
	return withInterceptors[[]*ASU_Watched_Class](ctx, awcq, qr, awcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) AllX(ctx context.Context) []*ASU_Watched_Class {
	nodes, err := awcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ASU_Watched_Class IDs.
func (awcq *ASUWatchedClassQuery) IDs(ctx context.Context) (ids []int, err error) {
	if awcq.ctx.Unique == nil && awcq.path != nil {
		awcq.Unique(true)
	}
	ctx = setContextOp(ctx, awcq.ctx, "IDs")
	if err = awcq.Select(asu_watched_class.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) IDsX(ctx context.Context) []int {
	ids, err := awcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (awcq *ASUWatchedClassQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, awcq.ctx, "Count")
	if err := awcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, awcq, querierCount[*ASUWatchedClassQuery](), awcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) CountX(ctx context.Context) int {
	count, err := awcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (awcq *ASUWatchedClassQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, awcq.ctx, "Exist")
	switch _, err := awcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (awcq *ASUWatchedClassQuery) ExistX(ctx context.Context) bool {
	exist, err := awcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ASUWatchedClassQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (awcq *ASUWatchedClassQuery) Clone() *ASUWatchedClassQuery {
	if awcq == nil {
		return nil
	}
	return &ASUWatchedClassQuery{
		config:     awcq.config,
		ctx:        awcq.ctx.Clone(),
		order:      append([]asu_watched_class.OrderOption{}, awcq.order...),
		inters:     append([]Interceptor{}, awcq.inters...),
		predicates: append([]predicate.ASU_Watched_Class{}, awcq.predicates...),
		// clone intermediate query.
		sql:  awcq.sql.Clone(),
		path: awcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ASUWatchedClass.Query().
//		GroupBy(asu_watched_class.FieldAge).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (awcq *ASUWatchedClassQuery) GroupBy(field string, fields ...string) *ASUWatchedClassGroupBy {
	awcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ASUWatchedClassGroupBy{build: awcq}
	grbuild.flds = &awcq.ctx.Fields
	grbuild.label = asu_watched_class.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//	}
//
//	client.ASUWatchedClass.Query().
//		Select(asu_watched_class.FieldAge).
//		Scan(ctx, &v)
func (awcq *ASUWatchedClassQuery) Select(fields ...string) *ASUWatchedClassSelect {
	awcq.ctx.Fields = append(awcq.ctx.Fields, fields...)
	sbuild := &ASUWatchedClassSelect{ASUWatchedClassQuery: awcq}
	sbuild.label = asu_watched_class.Label
	sbuild.flds, sbuild.scan = &awcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ASUWatchedClassSelect configured with the given aggregations.
func (awcq *ASUWatchedClassQuery) Aggregate(fns ...AggregateFunc) *ASUWatchedClassSelect {
	return awcq.Select().Aggregate(fns...)
}

func (awcq *ASUWatchedClassQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range awcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, awcq); err != nil {
				return err
			}
		}
	}
	for _, f := range awcq.ctx.Fields {
		if !asu_watched_class.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if awcq.path != nil {
		prev, err := awcq.path(ctx)
		if err != nil {
			return err
		}
		awcq.sql = prev
	}
	return nil
}

func (awcq *ASUWatchedClassQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ASU_Watched_Class, error) {
	var (
		nodes = []*ASU_Watched_Class{}
		_spec = awcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ASU_Watched_Class).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ASU_Watched_Class{config: awcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, awcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (awcq *ASUWatchedClassQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := awcq.querySpec()
	_spec.Node.Columns = awcq.ctx.Fields
	if len(awcq.ctx.Fields) > 0 {
		_spec.Unique = awcq.ctx.Unique != nil && *awcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, awcq.driver, _spec)
}

func (awcq *ASUWatchedClassQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(asu_watched_class.Table, asu_watched_class.Columns, sqlgraph.NewFieldSpec(asu_watched_class.FieldID, field.TypeInt))
	_spec.From = awcq.sql
	if unique := awcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if awcq.path != nil {
		_spec.Unique = true
	}
	if fields := awcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asu_watched_class.FieldID)
		for i := range fields {
			if fields[i] != asu_watched_class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := awcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := awcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := awcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := awcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (awcq *ASUWatchedClassQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(awcq.driver.Dialect())
	t1 := builder.Table(asu_watched_class.Table)
	columns := awcq.ctx.Fields
	if len(columns) == 0 {
		columns = asu_watched_class.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if awcq.sql != nil {
		selector = awcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if awcq.ctx.Unique != nil && *awcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range awcq.predicates {
		p(selector)
	}
	for _, p := range awcq.order {
		p(selector)
	}
	if offset := awcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := awcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ASUWatchedClassGroupBy is the group-by builder for ASU_Watched_Class entities.
type ASUWatchedClassGroupBy struct {
	selector
	build *ASUWatchedClassQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (awcgb *ASUWatchedClassGroupBy) Aggregate(fns ...AggregateFunc) *ASUWatchedClassGroupBy {
	awcgb.fns = append(awcgb.fns, fns...)
	return awcgb
}

// Scan applies the selector query and scans the result into the given value.
func (awcgb *ASUWatchedClassGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, awcgb.build.ctx, "GroupBy")
	if err := awcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ASUWatchedClassQuery, *ASUWatchedClassGroupBy](ctx, awcgb.build, awcgb, awcgb.build.inters, v)
}

func (awcgb *ASUWatchedClassGroupBy) sqlScan(ctx context.Context, root *ASUWatchedClassQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(awcgb.fns))
	for _, fn := range awcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*awcgb.flds)+len(awcgb.fns))
		for _, f := range *awcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*awcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := awcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ASUWatchedClassSelect is the builder for selecting fields of ASUWatchedClass entities.
type ASUWatchedClassSelect struct {
	*ASUWatchedClassQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (awcs *ASUWatchedClassSelect) Aggregate(fns ...AggregateFunc) *ASUWatchedClassSelect {
	awcs.fns = append(awcs.fns, fns...)
	return awcs
}

// Scan applies the selector query and scans the result into the given value.
func (awcs *ASUWatchedClassSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, awcs.ctx, "Select")
	if err := awcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ASUWatchedClassQuery, *ASUWatchedClassSelect](ctx, awcs.ASUWatchedClassQuery, awcs, awcs.inters, v)
}

func (awcs *ASUWatchedClassSelect) sqlScan(ctx context.Context, root *ASUWatchedClassQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(awcs.fns))
	for _, fn := range awcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*awcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := awcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
