// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asu_watched_class"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ASU_Watched_Class is the model entity for the ASU_Watched_Class schema.
type ASU_Watched_Class struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ASU_Watched_Class) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case asu_watched_class.FieldID, asu_watched_class.FieldAge:
			values[i] = new(sql.NullInt64)
		case asu_watched_class.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ASU_Watched_Class fields.
func (awc *ASU_Watched_Class) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case asu_watched_class.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			awc.ID = int(value.Int64)
		case asu_watched_class.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				awc.Age = int(value.Int64)
			}
		case asu_watched_class.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				awc.Name = value.String
			}
		default:
			awc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ASU_Watched_Class.
// This includes values selected through modifiers, order, etc.
func (awc *ASU_Watched_Class) Value(name string) (ent.Value, error) {
	return awc.selectValues.Get(name)
}

// Update returns a builder for updating this ASU_Watched_Class.
// Note that you need to call ASU_Watched_Class.Unwrap() before calling this method if this ASU_Watched_Class
// was returned from a transaction, and the transaction was committed or rolled back.
func (awc *ASU_Watched_Class) Update() *ASUWatchedClassUpdateOne {
	return NewASUWatchedClassClient(awc.config).UpdateOne(awc)
}

// Unwrap unwraps the ASU_Watched_Class entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (awc *ASU_Watched_Class) Unwrap() *ASU_Watched_Class {
	_tx, ok := awc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ASU_Watched_Class is not a transactional entity")
	}
	awc.config.driver = _tx.drv
	return awc
}

// String implements the fmt.Stringer.
func (awc *ASU_Watched_Class) String() string {
	var builder strings.Builder
	builder.WriteString("ASU_Watched_Class(")
	builder.WriteString(fmt.Sprintf("id=%v, ", awc.ID))
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", awc.Age))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(awc.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ASU_Watched_Classes is a parsable slice of ASU_Watched_Class.
type ASU_Watched_Classes []*ASU_Watched_Class
