// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asuwatchedclass"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ASUWatchedClass is the model entity for the ASUWatchedClass schema.
type ASUWatchedClass struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Instructor holds the value of the "instructor" field.
	Instructor string `json:"instructor,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// SubjectNumber holds the value of the "subject_number" field.
	SubjectNumber string `json:"subject_number,omitempty"`
	// TrackedAt holds the value of the "tracked_at" field.
	TrackedAt time.Time `json:"tracked_at,omitempty"`
	// ClassNumber holds the value of the "class_number" field.
	ClassNumber string `json:"class_number,omitempty"`
	// Term holds the value of the "term" field.
	Term         string `json:"term,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ASUWatchedClass) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case asuwatchedclass.FieldID:
			values[i] = new(sql.NullInt64)
		case asuwatchedclass.FieldUserID, asuwatchedclass.FieldTitle, asuwatchedclass.FieldInstructor, asuwatchedclass.FieldSubject, asuwatchedclass.FieldSubjectNumber, asuwatchedclass.FieldClassNumber, asuwatchedclass.FieldTerm:
			values[i] = new(sql.NullString)
		case asuwatchedclass.FieldTrackedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ASUWatchedClass fields.
func (awc *ASUWatchedClass) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case asuwatchedclass.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			awc.ID = int(value.Int64)
		case asuwatchedclass.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				awc.UserID = value.String
			}
		case asuwatchedclass.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				awc.Title = value.String
			}
		case asuwatchedclass.FieldInstructor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instructor", values[i])
			} else if value.Valid {
				awc.Instructor = value.String
			}
		case asuwatchedclass.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				awc.Subject = value.String
			}
		case asuwatchedclass.FieldSubjectNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_number", values[i])
			} else if value.Valid {
				awc.SubjectNumber = value.String
			}
		case asuwatchedclass.FieldTrackedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field tracked_at", values[i])
			} else if value.Valid {
				awc.TrackedAt = value.Time
			}
		case asuwatchedclass.FieldClassNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field class_number", values[i])
			} else if value.Valid {
				awc.ClassNumber = value.String
			}
		case asuwatchedclass.FieldTerm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field term", values[i])
			} else if value.Valid {
				awc.Term = value.String
			}
		default:
			awc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ASUWatchedClass.
// This includes values selected through modifiers, order, etc.
func (awc *ASUWatchedClass) Value(name string) (ent.Value, error) {
	return awc.selectValues.Get(name)
}

// Update returns a builder for updating this ASUWatchedClass.
// Note that you need to call ASUWatchedClass.Unwrap() before calling this method if this ASUWatchedClass
// was returned from a transaction, and the transaction was committed or rolled back.
func (awc *ASUWatchedClass) Update() *ASUWatchedClassUpdateOne {
	return NewASUWatchedClassClient(awc.config).UpdateOne(awc)
}

// Unwrap unwraps the ASUWatchedClass entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (awc *ASUWatchedClass) Unwrap() *ASUWatchedClass {
	_tx, ok := awc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ASUWatchedClass is not a transactional entity")
	}
	awc.config.driver = _tx.drv
	return awc
}

// String implements the fmt.Stringer.
func (awc *ASUWatchedClass) String() string {
	var builder strings.Builder
	builder.WriteString("ASUWatchedClass(")
	builder.WriteString(fmt.Sprintf("id=%v, ", awc.ID))
	builder.WriteString("user_id=")
	builder.WriteString(awc.UserID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(awc.Title)
	builder.WriteString(", ")
	builder.WriteString("instructor=")
	builder.WriteString(awc.Instructor)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(awc.Subject)
	builder.WriteString(", ")
	builder.WriteString("subject_number=")
	builder.WriteString(awc.SubjectNumber)
	builder.WriteString(", ")
	builder.WriteString("tracked_at=")
	builder.WriteString(awc.TrackedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("class_number=")
	builder.WriteString(awc.ClassNumber)
	builder.WriteString(", ")
	builder.WriteString("term=")
	builder.WriteString(awc.Term)
	builder.WriteByte(')')
	return builder.String()
}

// ASUWatchedClasses is a parsable slice of ASUWatchedClass.
type ASUWatchedClasses []*ASUWatchedClass
