// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asuwatchedclass"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ASUWatchedClassCreate is the builder for creating a ASUWatchedClass entity.
type ASUWatchedClassCreate struct {
	config
	mutation *ASUWatchedClassMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (awcc *ASUWatchedClassCreate) SetUserID(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetUserID(s)
	return awcc
}

// SetTitle sets the "title" field.
func (awcc *ASUWatchedClassCreate) SetTitle(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetTitle(s)
	return awcc
}

// SetInstructor sets the "instructor" field.
func (awcc *ASUWatchedClassCreate) SetInstructor(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetInstructor(s)
	return awcc
}

// SetSubject sets the "subject" field.
func (awcc *ASUWatchedClassCreate) SetSubject(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetSubject(s)
	return awcc
}

// SetSubjectNumber sets the "subject_number" field.
func (awcc *ASUWatchedClassCreate) SetSubjectNumber(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetSubjectNumber(s)
	return awcc
}

// SetTrackedAt sets the "tracked_at" field.
func (awcc *ASUWatchedClassCreate) SetTrackedAt(t time.Time) *ASUWatchedClassCreate {
	awcc.mutation.SetTrackedAt(t)
	return awcc
}

// SetNillableTrackedAt sets the "tracked_at" field if the given value is not nil.
func (awcc *ASUWatchedClassCreate) SetNillableTrackedAt(t *time.Time) *ASUWatchedClassCreate {
	if t != nil {
		awcc.SetTrackedAt(*t)
	}
	return awcc
}

// SetClassNumber sets the "class_number" field.
func (awcc *ASUWatchedClassCreate) SetClassNumber(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetClassNumber(s)
	return awcc
}

// SetTerm sets the "term" field.
func (awcc *ASUWatchedClassCreate) SetTerm(s string) *ASUWatchedClassCreate {
	awcc.mutation.SetTerm(s)
	return awcc
}

// SetID sets the "id" field.
func (awcc *ASUWatchedClassCreate) SetID(i int) *ASUWatchedClassCreate {
	awcc.mutation.SetID(i)
	return awcc
}

// Mutation returns the ASUWatchedClassMutation object of the builder.
func (awcc *ASUWatchedClassCreate) Mutation() *ASUWatchedClassMutation {
	return awcc.mutation
}

// Save creates the ASUWatchedClass in the database.
func (awcc *ASUWatchedClassCreate) Save(ctx context.Context) (*ASUWatchedClass, error) {
	return withHooks(ctx, awcc.sqlSave, awcc.mutation, awcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (awcc *ASUWatchedClassCreate) SaveX(ctx context.Context) *ASUWatchedClass {
	v, err := awcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (awcc *ASUWatchedClassCreate) Exec(ctx context.Context) error {
	_, err := awcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (awcc *ASUWatchedClassCreate) ExecX(ctx context.Context) {
	if err := awcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (awcc *ASUWatchedClassCreate) check() error {
	if _, ok := awcc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ASUWatchedClass.user_id"`)}
	}
	if _, ok := awcc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ASUWatchedClass.title"`)}
	}
	if _, ok := awcc.mutation.Instructor(); !ok {
		return &ValidationError{Name: "instructor", err: errors.New(`ent: missing required field "ASUWatchedClass.instructor"`)}
	}
	if _, ok := awcc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "ASUWatchedClass.subject"`)}
	}
	if _, ok := awcc.mutation.SubjectNumber(); !ok {
		return &ValidationError{Name: "subject_number", err: errors.New(`ent: missing required field "ASUWatchedClass.subject_number"`)}
	}
	if _, ok := awcc.mutation.ClassNumber(); !ok {
		return &ValidationError{Name: "class_number", err: errors.New(`ent: missing required field "ASUWatchedClass.class_number"`)}
	}
	if _, ok := awcc.mutation.Term(); !ok {
		return &ValidationError{Name: "term", err: errors.New(`ent: missing required field "ASUWatchedClass.term"`)}
	}
	return nil
}

func (awcc *ASUWatchedClassCreate) sqlSave(ctx context.Context) (*ASUWatchedClass, error) {
	if err := awcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := awcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, awcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	awcc.mutation.id = &_node.ID
	awcc.mutation.done = true
	return _node, nil
}

func (awcc *ASUWatchedClassCreate) createSpec() (*ASUWatchedClass, *sqlgraph.CreateSpec) {
	var (
		_node = &ASUWatchedClass{config: awcc.config}
		_spec = sqlgraph.NewCreateSpec(asuwatchedclass.Table, sqlgraph.NewFieldSpec(asuwatchedclass.FieldID, field.TypeInt))
	)
	if id, ok := awcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := awcc.mutation.UserID(); ok {
		_spec.SetField(asuwatchedclass.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := awcc.mutation.Title(); ok {
		_spec.SetField(asuwatchedclass.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := awcc.mutation.Instructor(); ok {
		_spec.SetField(asuwatchedclass.FieldInstructor, field.TypeString, value)
		_node.Instructor = value
	}
	if value, ok := awcc.mutation.Subject(); ok {
		_spec.SetField(asuwatchedclass.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := awcc.mutation.SubjectNumber(); ok {
		_spec.SetField(asuwatchedclass.FieldSubjectNumber, field.TypeString, value)
		_node.SubjectNumber = value
	}
	if value, ok := awcc.mutation.TrackedAt(); ok {
		_spec.SetField(asuwatchedclass.FieldTrackedAt, field.TypeTime, value)
		_node.TrackedAt = value
	}
	if value, ok := awcc.mutation.ClassNumber(); ok {
		_spec.SetField(asuwatchedclass.FieldClassNumber, field.TypeString, value)
		_node.ClassNumber = value
	}
	if value, ok := awcc.mutation.Term(); ok {
		_spec.SetField(asuwatchedclass.FieldTerm, field.TypeString, value)
		_node.Term = value
	}
	return _node, _spec
}

// ASUWatchedClassCreateBulk is the builder for creating many ASUWatchedClass entities in bulk.
type ASUWatchedClassCreateBulk struct {
	config
	builders []*ASUWatchedClassCreate
}

// Save creates the ASUWatchedClass entities in the database.
func (awccb *ASUWatchedClassCreateBulk) Save(ctx context.Context) ([]*ASUWatchedClass, error) {
	specs := make([]*sqlgraph.CreateSpec, len(awccb.builders))
	nodes := make([]*ASUWatchedClass, len(awccb.builders))
	mutators := make([]Mutator, len(awccb.builders))
	for i := range awccb.builders {
		func(i int, root context.Context) {
			builder := awccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ASUWatchedClassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, awccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, awccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, awccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (awccb *ASUWatchedClassCreateBulk) SaveX(ctx context.Context) []*ASUWatchedClass {
	v, err := awccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (awccb *ASUWatchedClassCreateBulk) Exec(ctx context.Context) error {
	_, err := awccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (awccb *ASUWatchedClassCreateBulk) ExecX(ctx context.Context) {
	if err := awccb.Exec(ctx); err != nil {
		panic(err)
	}
}
