// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asu_watched_class"
	"attendr/watcher/ent/predicate"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeASUWatchedClass = "ASU_Watched_Class"
)

// ASUWatchedClassMutation represents an operation that mutates the ASU_Watched_Class nodes in the graph.
type ASUWatchedClassMutation struct {
	config
	op             Op
	typ            string
	id             *int
	title          *string
	instructor     *string
	subject        *string
	subject_number *string
	has_open_seats *bool
	tracked_at     *time.Time
	class_number   *string
	term           *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*ASU_Watched_Class, error)
	predicates     []predicate.ASU_Watched_Class
}

var _ ent.Mutation = (*ASUWatchedClassMutation)(nil)

// asuWatchedClassOption allows management of the mutation configuration using functional options.
type asuWatchedClassOption func(*ASUWatchedClassMutation)

// newASUWatchedClassMutation creates new mutation for the ASU_Watched_Class entity.
func newASUWatchedClassMutation(c config, op Op, opts ...asuWatchedClassOption) *ASUWatchedClassMutation {
	m := &ASUWatchedClassMutation{
		config:        c,
		op:            op,
		typ:           TypeASUWatchedClass,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withASU_Watched_ClassID sets the ID field of the mutation.
func withASU_Watched_ClassID(id int) asuWatchedClassOption {
	return func(m *ASUWatchedClassMutation) {
		var (
			err   error
			once  sync.Once
			value *ASU_Watched_Class
		)
		m.oldValue = func(ctx context.Context) (*ASU_Watched_Class, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ASU_Watched_Class.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withASU_Watched_Class sets the old ASU_Watched_Class of the mutation.
func withASU_Watched_Class(node *ASU_Watched_Class) asuWatchedClassOption {
	return func(m *ASUWatchedClassMutation) {
		m.oldValue = func(context.Context) (*ASU_Watched_Class, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ASUWatchedClassMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ASUWatchedClassMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ASU_Watched_Class entities.
func (m *ASUWatchedClassMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ASUWatchedClassMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ASUWatchedClassMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ASU_Watched_Class.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *ASUWatchedClassMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ASUWatchedClassMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ASUWatchedClassMutation) ResetTitle() {
	m.title = nil
}

// SetInstructor sets the "instructor" field.
func (m *ASUWatchedClassMutation) SetInstructor(s string) {
	m.instructor = &s
}

// Instructor returns the value of the "instructor" field in the mutation.
func (m *ASUWatchedClassMutation) Instructor() (r string, exists bool) {
	v := m.instructor
	if v == nil {
		return
	}
	return *v, true
}

// OldInstructor returns the old "instructor" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldInstructor(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstructor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstructor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstructor: %w", err)
	}
	return oldValue.Instructor, nil
}

// ResetInstructor resets all changes to the "instructor" field.
func (m *ASUWatchedClassMutation) ResetInstructor() {
	m.instructor = nil
}

// SetSubject sets the "subject" field.
func (m *ASUWatchedClassMutation) SetSubject(s string) {
	m.subject = &s
}

// Subject returns the value of the "subject" field in the mutation.
func (m *ASUWatchedClassMutation) Subject() (r string, exists bool) {
	v := m.subject
	if v == nil {
		return
	}
	return *v, true
}

// OldSubject returns the old "subject" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubject: %w", err)
	}
	return oldValue.Subject, nil
}

// ResetSubject resets all changes to the "subject" field.
func (m *ASUWatchedClassMutation) ResetSubject() {
	m.subject = nil
}

// SetSubjectNumber sets the "subject_number" field.
func (m *ASUWatchedClassMutation) SetSubjectNumber(s string) {
	m.subject_number = &s
}

// SubjectNumber returns the value of the "subject_number" field in the mutation.
func (m *ASUWatchedClassMutation) SubjectNumber() (r string, exists bool) {
	v := m.subject_number
	if v == nil {
		return
	}
	return *v, true
}

// OldSubjectNumber returns the old "subject_number" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldSubjectNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubjectNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubjectNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubjectNumber: %w", err)
	}
	return oldValue.SubjectNumber, nil
}

// ResetSubjectNumber resets all changes to the "subject_number" field.
func (m *ASUWatchedClassMutation) ResetSubjectNumber() {
	m.subject_number = nil
}

// SetHasOpenSeats sets the "has_open_seats" field.
func (m *ASUWatchedClassMutation) SetHasOpenSeats(b bool) {
	m.has_open_seats = &b
}

// HasOpenSeats returns the value of the "has_open_seats" field in the mutation.
func (m *ASUWatchedClassMutation) HasOpenSeats() (r bool, exists bool) {
	v := m.has_open_seats
	if v == nil {
		return
	}
	return *v, true
}

// OldHasOpenSeats returns the old "has_open_seats" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldHasOpenSeats(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHasOpenSeats is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHasOpenSeats requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHasOpenSeats: %w", err)
	}
	return oldValue.HasOpenSeats, nil
}

// ResetHasOpenSeats resets all changes to the "has_open_seats" field.
func (m *ASUWatchedClassMutation) ResetHasOpenSeats() {
	m.has_open_seats = nil
}

// SetTrackedAt sets the "tracked_at" field.
func (m *ASUWatchedClassMutation) SetTrackedAt(t time.Time) {
	m.tracked_at = &t
}

// TrackedAt returns the value of the "tracked_at" field in the mutation.
func (m *ASUWatchedClassMutation) TrackedAt() (r time.Time, exists bool) {
	v := m.tracked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldTrackedAt returns the old "tracked_at" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldTrackedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTrackedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTrackedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTrackedAt: %w", err)
	}
	return oldValue.TrackedAt, nil
}

// ResetTrackedAt resets all changes to the "tracked_at" field.
func (m *ASUWatchedClassMutation) ResetTrackedAt() {
	m.tracked_at = nil
}

// SetClassNumber sets the "class_number" field.
func (m *ASUWatchedClassMutation) SetClassNumber(s string) {
	m.class_number = &s
}

// ClassNumber returns the value of the "class_number" field in the mutation.
func (m *ASUWatchedClassMutation) ClassNumber() (r string, exists bool) {
	v := m.class_number
	if v == nil {
		return
	}
	return *v, true
}

// OldClassNumber returns the old "class_number" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldClassNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClassNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClassNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClassNumber: %w", err)
	}
	return oldValue.ClassNumber, nil
}

// ResetClassNumber resets all changes to the "class_number" field.
func (m *ASUWatchedClassMutation) ResetClassNumber() {
	m.class_number = nil
}

// SetTerm sets the "term" field.
func (m *ASUWatchedClassMutation) SetTerm(s string) {
	m.term = &s
}

// Term returns the value of the "term" field in the mutation.
func (m *ASUWatchedClassMutation) Term() (r string, exists bool) {
	v := m.term
	if v == nil {
		return
	}
	return *v, true
}

// OldTerm returns the old "term" field's value of the ASU_Watched_Class entity.
// If the ASU_Watched_Class object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ASUWatchedClassMutation) OldTerm(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTerm is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTerm requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTerm: %w", err)
	}
	return oldValue.Term, nil
}

// ResetTerm resets all changes to the "term" field.
func (m *ASUWatchedClassMutation) ResetTerm() {
	m.term = nil
}

// Where appends a list predicates to the ASUWatchedClassMutation builder.
func (m *ASUWatchedClassMutation) Where(ps ...predicate.ASU_Watched_Class) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ASUWatchedClassMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ASUWatchedClassMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ASU_Watched_Class, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ASUWatchedClassMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ASUWatchedClassMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ASU_Watched_Class).
func (m *ASUWatchedClassMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ASUWatchedClassMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.title != nil {
		fields = append(fields, asu_watched_class.FieldTitle)
	}
	if m.instructor != nil {
		fields = append(fields, asu_watched_class.FieldInstructor)
	}
	if m.subject != nil {
		fields = append(fields, asu_watched_class.FieldSubject)
	}
	if m.subject_number != nil {
		fields = append(fields, asu_watched_class.FieldSubjectNumber)
	}
	if m.has_open_seats != nil {
		fields = append(fields, asu_watched_class.FieldHasOpenSeats)
	}
	if m.tracked_at != nil {
		fields = append(fields, asu_watched_class.FieldTrackedAt)
	}
	if m.class_number != nil {
		fields = append(fields, asu_watched_class.FieldClassNumber)
	}
	if m.term != nil {
		fields = append(fields, asu_watched_class.FieldTerm)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ASUWatchedClassMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case asu_watched_class.FieldTitle:
		return m.Title()
	case asu_watched_class.FieldInstructor:
		return m.Instructor()
	case asu_watched_class.FieldSubject:
		return m.Subject()
	case asu_watched_class.FieldSubjectNumber:
		return m.SubjectNumber()
	case asu_watched_class.FieldHasOpenSeats:
		return m.HasOpenSeats()
	case asu_watched_class.FieldTrackedAt:
		return m.TrackedAt()
	case asu_watched_class.FieldClassNumber:
		return m.ClassNumber()
	case asu_watched_class.FieldTerm:
		return m.Term()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ASUWatchedClassMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case asu_watched_class.FieldTitle:
		return m.OldTitle(ctx)
	case asu_watched_class.FieldInstructor:
		return m.OldInstructor(ctx)
	case asu_watched_class.FieldSubject:
		return m.OldSubject(ctx)
	case asu_watched_class.FieldSubjectNumber:
		return m.OldSubjectNumber(ctx)
	case asu_watched_class.FieldHasOpenSeats:
		return m.OldHasOpenSeats(ctx)
	case asu_watched_class.FieldTrackedAt:
		return m.OldTrackedAt(ctx)
	case asu_watched_class.FieldClassNumber:
		return m.OldClassNumber(ctx)
	case asu_watched_class.FieldTerm:
		return m.OldTerm(ctx)
	}
	return nil, fmt.Errorf("unknown ASU_Watched_Class field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ASUWatchedClassMutation) SetField(name string, value ent.Value) error {
	switch name {
	case asu_watched_class.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case asu_watched_class.FieldInstructor:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstructor(v)
		return nil
	case asu_watched_class.FieldSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubject(v)
		return nil
	case asu_watched_class.FieldSubjectNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubjectNumber(v)
		return nil
	case asu_watched_class.FieldHasOpenSeats:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHasOpenSeats(v)
		return nil
	case asu_watched_class.FieldTrackedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTrackedAt(v)
		return nil
	case asu_watched_class.FieldClassNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClassNumber(v)
		return nil
	case asu_watched_class.FieldTerm:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTerm(v)
		return nil
	}
	return fmt.Errorf("unknown ASU_Watched_Class field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ASUWatchedClassMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ASUWatchedClassMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ASUWatchedClassMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ASU_Watched_Class numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ASUWatchedClassMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ASUWatchedClassMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ASUWatchedClassMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ASU_Watched_Class nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ASUWatchedClassMutation) ResetField(name string) error {
	switch name {
	case asu_watched_class.FieldTitle:
		m.ResetTitle()
		return nil
	case asu_watched_class.FieldInstructor:
		m.ResetInstructor()
		return nil
	case asu_watched_class.FieldSubject:
		m.ResetSubject()
		return nil
	case asu_watched_class.FieldSubjectNumber:
		m.ResetSubjectNumber()
		return nil
	case asu_watched_class.FieldHasOpenSeats:
		m.ResetHasOpenSeats()
		return nil
	case asu_watched_class.FieldTrackedAt:
		m.ResetTrackedAt()
		return nil
	case asu_watched_class.FieldClassNumber:
		m.ResetClassNumber()
		return nil
	case asu_watched_class.FieldTerm:
		m.ResetTerm()
		return nil
	}
	return fmt.Errorf("unknown ASU_Watched_Class field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ASUWatchedClassMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ASUWatchedClassMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ASUWatchedClassMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ASUWatchedClassMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ASUWatchedClassMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ASUWatchedClassMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ASUWatchedClassMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ASU_Watched_Class unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ASUWatchedClassMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ASU_Watched_Class edge %s", name)
}
