// Code generated by ent, DO NOT EDIT.

package ent

import (
	"attendr/watcher/ent/asu_watched_class"
	"attendr/watcher/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	asu_watched_classFields := schema.ASU_Watched_Class{}.Fields()
	_ = asu_watched_classFields
	// asu_watched_classDescAge is the schema descriptor for age field.
	asu_watched_classDescAge := asu_watched_classFields[0].Descriptor()
	// asu_watched_class.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	asu_watched_class.AgeValidator = asu_watched_classDescAge.Validators[0].(func(int) error)
	// asu_watched_classDescName is the schema descriptor for name field.
	asu_watched_classDescName := asu_watched_classFields[1].Descriptor()
	// asu_watched_class.DefaultName holds the default value on creation for the name field.
	asu_watched_class.DefaultName = asu_watched_classDescName.Default.(string)
}
