package asu

/*
* In general, the API response is used throughout the program to store API data
* However, only the first index "0" is used to access data, as we are querying
* with a single class number, and expect a single class in return.
**/
type ApiResponse struct {
	Classes []struct {
		Clas struct {
			Strm                              string     `json:"STRM"`
			Classnbr                          string     `json:"CLASSNBR"`
			Crseid                            string     `json:"CRSEID"`
			Crseoffernbr                      string     `json:"CRSEOFFERNBR"`
			Classsection                      string     `json:"CLASSSECTION"`
			Sessioncode                       string     `json:"SESSIONCODE"`
			Classmtgnbr                       string     `json:"CLASSMTGNBR"`
			Subject                           string     `json:"SUBJECT"`
			Subjectforsorting                 string     `json:"SUBJECTFORSORTING"`
			Catalognbr                        string     `json:"CATALOGNBR"`
			Catalognbrforsorting              string     `json:"CATALOGNBRFORSORTING"`
			Campus                            string     `json:"CAMPUS"`
			Descr                             string     `json:"DESCR"`
			Location                          string     `json:"LOCATION"`
			Descr3                            string     `json:"DESCR3"`
			Title                             string     `json:"TITLE"`
			Titleforsorting                   string     `json:"TITLEFORSORTING"`
			Coursetitlelong                   string     `json:"COURSETITLELONG"`
			Startdate                         string     `json:"STARTDATE"`
			Starttime                         string     `json:"STARTTIME"`
			Enddate                           string     `json:"ENDDATE"`
			Endtime                           string     `json:"ENDTIME"`
			Mon                               string     `json:"MON"`
			Tues                              string     `json:"TUES"`
			Wed                               string     `json:"WED"`
			Thurs                             string     `json:"THURS"`
			Fri                               string     `json:"FRI"`
			Sat                               string     `json:"SAT"`
			Sun                               string     `json:"SUN"`
			Scheduleprint                     string     `json:"SCHEDULEPRINT"`
			Facilityid                        string     `json:"FACILITYID"`
			Descr1                            string     `json:"DESCR1"`
			Instrrole                         string     `json:"INSTRROLE"`
			Enrltot                           string     `json:"ENRLTOT"`
			Enrlcap                           string     `json:"ENRLCAP"`
			Waittot                           string     `json:"WAITTOT"`
			Waitcap                           string     `json:"WAITCAP"`
			Rqmntdesigntn                     string     `json:"RQMNTDESIGNTN"`
			Descr4                            string     `json:"DESCR4"`
			Descrformal                       string     `json:"DESCRFORMAL"`
			Classnotesseq                     string     `json:"CLASSNOTESSEQ"`
			Descrlong                         string     `json:"DESCRLONG"`
			Acadcareer                        string     `json:"ACADCAREER"`
			Componentprimary                  string     `json:"COMPONENTPRIMARY"`
			Descr2                            string     `json:"DESCR2"`
			Unitsminimum                      string     `json:"UNITSMINIMUM"`
			Unitsmaximum                      string     `json:"UNITSMAXIMUM"`
			Flatamount1                       string     `json:"FLATAMOUNT1"`
			Flatamount2                       string     `json:"FLATAMOUNT2"`
			Associatedclass                   string     `json:"ASSOCIATEDCLASS"`
			Ssrcomponent                      string     `json:"SSRCOMPONENT"`
			Xlatlongname                      string     `json:"XLATLONGNAME"`
			Optionalsection                   string     `json:"OPTIONALSECTION"`
			Countrows                         string     `json:"COUNTROWS"`
			Consent                           string     `json:"CONSENT"`
			Crstopicid                        string     `json:"CRSTOPICID"`
			Descr50                           string     `json:"DESCR50"`
			Enrlstat                          string     `json:"ENRLSTAT"`
			Classstat                         string     `json:"CLASSSTAT"`
			Instructionmode                   string     `json:"INSTRUCTIONMODE"`
			Sctncombinedid                    string     `json:"SCTNCOMBINEDID"`
			Acadgroup                         string     `json:"ACADGROUP"`
			Descr5                            string     `json:"DESCR5"`
			Acadorg                           string     `json:"ACADORG"`
			Descr501                          string     `json:"DESCR501"`
			Descr6                            string     `json:"DESCR6"`
			Schedprintinstr                   string     `json:"SCHEDPRINTINSTR"`
			Asubldlocation                    string     `json:"ASUBLDLOCATION"`
			Asubldname                        string     `json:"ASUBLDNAME"`
			Crseid1                           any        `json:"CRSEID1"`
			Crseoffernbr1                     any        `json:"CRSEOFFERNBR1"`
			Crserepeatable                    string     `json:"CRSEREPEATABLE"`
			Gradingbasis                      any        `json:"GRADINGBASIS"`
			Xlatlongname1                     any        `json:"XLATLONGNAME1"`
			Feesexist                         any        `json:"FEESEXIST"`
			Descrlong1                        any        `json:"DESCRLONG1"`
			Rqrmntgroup                       any        `json:"RQRMNTGROUP"`
			Descr31                           any        `json:"DESCR31"`
			Descr254A                         any        `json:"DESCR254A"`
			Rqmntdesigntn1                    any        `json:"RQMNTDESIGNTN1"`
			Descr41                           any        `json:"DESCR41"`
			Descrformal1                      any        `json:"DESCRFORMAL1"`
			Classtype                         string     `json:"CLASSTYPE"`
			Termbegindate                     string     `json:"TERMBEGINDATE"`
			Termenddate                       string     `json:"TERMENDDATE"`
			Capnbr                            string     `json:"CAPNBR"`
			Capstartdate                      string     `json:"CAPSTARTDATE"`
			Enrolldeadline                    string     `json:"ENROLLDEADLINE"`
			Dropretainrecord                  string     `json:"DROPRETAINRECORD"`
			Dropwithpenalty                   string     `json:"DROPWITHPENALTY"`
			Withdrawwithpenalty               string     `json:"WITHDRAWWITHPENALTY"`
			Promod                            string     `json:"PROMOD"`
			Instructoredit                    string     `json:"INSTRUCTOREDIT"`
			Officialstartdate                 string     `json:"OFFICIALSTARTDATE"`
			Officialenddate                   string     `json:"OFFICIALENDDATE"`
			Promodcohortcd                    any        `json:"PROMODCOHORTCD"`
			Classdescr                        string     `json:"CLASSDESCR"`
			Lastfullupdatetimestamp           int64      `json:"LASTFULLUPDATETIMESTAMP"`
			Keywordsearchstr                  string     `json:"KEYWORDSEARCHSTR"`
			Classnotenbr                      string     `json:"CLASSNOTENBR"`
			Crseatteffdt                      string     `json:"CRSEATTEFFDT"`
			Crseattvalue                      string     `json:"CRSEATTVALUE"`
			Ssrcount                          int        `json:"SSRCOUNT"`
			Hasactivereservedseats            string     `json:"HASACTIVERESERVEDSEATS"`
			Daylist                           string     `json:"DAYLIST"`
			Notes                             []any      `json:"NOTES"`
			Notesnumbers                      []any      `json:"NOTESNUMBERS"`
			Iframenotes                       any        `json:"IFRAMENOTES"`
			Ssr                               string     `json:"SSR"`
			Passenrolldeadline                any        `json:"PASSENROLLDEADLINE"`
			Passterm                          string     `json:"PASSTERM"`
			Showsunnum                        string     `json:"SHOWSUNNUM"`
			Mtgdatesstrtime                   any        `json:"MTGDATESSTRTIME"`
			Multiplemtgdates                  string     `json:"MULTIPLEMTGDATES"`
			Locationbuilding                  string     `json:"LOCATIONBUILDING"`
			Bldgcd                            any        `json:"BLDGCD"`
			Address1                          string     `json:"ADDRESS1"`
			Address2                          string     `json:"ADDRESS2"`
			Address3                          string     `json:"ADDRESS3"`
			City                              string     `json:"CITY"`
			State                             string     `json:"STATE"`
			Asubldaddress                     string     `json:"ASUBLDADDRESS"`
			Subjectdescription                string     `json:"SUBJECTDESCRIPTION"`
			Instructorslastnamelist           []string   `json:"INSTRUCTORSLASTNAMELIST"`
			Instructorsfirstnamelist          []string   `json:"INSTRUCTORSFIRSTNAMELIST"`
			Instructorslist                   []string   `json:"INSTRUCTORSLIST"`
			Instructorsfirstnameshowall       []string   `json:"INSTRUCTORSFIRSTNAMESHOWALL"`
			Instructorslastnameshowall        []string   `json:"INSTRUCTORSLASTNAMESHOWALL"`
			Instructorlistforkeyword          string     `json:"INSTRUCTORLISTFORKEYWORD"`
			Instructorslastnamelistforsorting string     `json:"INSTRUCTORSLASTNAMELISTFORSORTING"`
			Meetingdates                      [][]string `json:"MEETINGDATES"`
			Meetingdatesforsorting            int64      `json:"MEETINGDATESFORSORTING"`
			Starttimes                        []any      `json:"STARTTIMES"`
			Endtimes                          []any      `json:"ENDTIMES"`
			Starttimesforsorting              string     `json:"STARTTIMESFORSORTING"`
			ShortDesc                         string     `json:"SHORT_DESC"`
			Starttimeformatted                string     `json:"STARTTIMEFORMATTED"`
			Endtimeformatted                  string     `json:"ENDTIMEFORMATTED"`
			Classdays                         string     `json:"CLASSDAYS"`
			Catalognbrnumber                  int        `json:"CATALOGNBRNUMBER"`
			Unitsrange                        string     `json:"UNITSRANGE"`
			Associatedclassnotnull            string     `json:"ASSOCIATEDCLASSNOTNULL"`
			ID                                string     `json:"id"`
		} `json:"CLAS"`
		Subjectnumber      string   `json:"SUBJECTNUMBER"`
		Sectionclassnumber string   `json:"SECTIONCLASSNUMBER"`
		Daylist            []string `json:"DAYLIST"`
		Notes              string   `json:"NOTES"`
		Hours              string   `json:"HOURS"`
		Ssr                string   `json:"SSR"`
		Locationbuilding   []struct {
			Nameforsorting string `json:"NAMEFORSORTING"`
			Name           string `json:"NAME"`
			Descr          string `json:"DESCR"`
			Address        string `json:"ADDRESS"`
			URL            string `json:"URL"`
		} `json:"LOCATIONBUILDING"`
		Meetingstartdates []any  `json:"MEETINGSTARTDATES"`
		Mtgdates          []any  `json:"MTGDATES"`
		Grouporg          string `json:"GROUPORG"`
		Keywordmatch      struct {
			Value       int    `json:"value"`
			Description string `json:"description"`
			Details     []any  `json:"details"`
		} `json:"KEYWORDMATCH"`
		Offeredby struct {
			Department string `json:"DEPARTMENT"`
			Info       struct {
				Acadorg       string `json:"ACADORG"`
				Asucollegeurl string `json:"ASUCOLLEGEURL"`
				Descrformal   string `json:"DESCRFORMAL"`
				Enrollreq     any    `json:"ENROLLREQ"`
				Acadgroup     string `json:"ACADGROUP"`
			} `json:"INFO"`
		} `json:"OFFEREDBY"`
		Hassyllabus bool `json:"HASSYLLABUS"`
		SeatInfo    struct {
			EnrlCap int `json:"ENRL_CAP"`
			EnrlTot int `json:"ENRL_TOT"`
		} `json:"seatInfo"`
	} `json:"classes"`
	Aggregations struct {
		Location struct{} `json:"LOCATION"`
		College  struct{} `json:"COLLEGE"`
	} `json:"aggregations"`
	ScrollID string `json:"scrollId"`
	Total    struct {
		Value    int    `json:"value"`
		Relation string `json:"relation"`
	} `json:"total"`
}
