// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AsuWatchedClassesColumns holds the columns for the "asu_watched_classes" table.
	AsuWatchedClassesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// AsuWatchedClassesTable holds the schema information for the "asu_watched_classes" table.
	AsuWatchedClassesTable = &schema.Table{
		Name:       "asu_watched_classes",
		Columns:    AsuWatchedClassesColumns,
		PrimaryKey: []*schema.Column{AsuWatchedClassesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AsuWatchedClassesTable,
	}
)

func init() {
}
