// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ASUWatchedClassesColumns holds the columns for the "ASU_Watched_Classes" table.
	ASUWatchedClassesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "instructor", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "subject_number", Type: field.TypeString},
		{Name: "tracked_at", Type: field.TypeTime, Nullable: true},
		{Name: "class_number", Type: field.TypeString},
		{Name: "term", Type: field.TypeString},
	}
	// ASUWatchedClassesTable holds the schema information for the "ASU_Watched_Classes" table.
	ASUWatchedClassesTable = &schema.Table{
		Name:       "ASU_Watched_Classes",
		Columns:    ASUWatchedClassesColumns,
		PrimaryKey: []*schema.Column{ASUWatchedClassesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ASUWatchedClassesTable,
	}
)

func init() {
	ASUWatchedClassesTable.Annotation = &entsql.Annotation{
		Table: "ASU_Watched_Classes",
	}
}
