// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AsuWatchedClassesColumns holds the columns for the "asu_watched_classes" table.
	AsuWatchedClassesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "instructor", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "subject_number", Type: field.TypeString},
		{Name: "has_open_seats", Type: field.TypeBool, Default: false},
		{Name: "tracked_at", Type: field.TypeTime},
		{Name: "class_number", Type: field.TypeString, Unique: true},
		{Name: "term", Type: field.TypeString},
	}
	// AsuWatchedClassesTable holds the schema information for the "asu_watched_classes" table.
	AsuWatchedClassesTable = &schema.Table{
		Name:       "asu_watched_classes",
		Columns:    AsuWatchedClassesColumns,
		PrimaryKey: []*schema.Column{AsuWatchedClassesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AsuWatchedClassesTable,
	}
)

func init() {
}
